{% set version = "0.1.0" %}

package:
  name: pyhat
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/PyHAT
  git_rev: dev

build:
  number: 2
  skip: True  # [not py3k]
  
requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - scipy
    - plio
    - pandas
  run:
    - python
    - numpy >=1.10
    - scipy
    - plio
    - pandas

test:
  imports:
    - libpyhat

about:
  home: https://github.com/USGS-Astrogeology/PyHAT
  license: Unlicense
