language: python
cache:
  - pip
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
script:
  - bash build.sh
  - python setup.py sdist
deploy:
  provider: pypi
  user: tisaconundrum
  password:
  distributions: sdist bdist_wheel
  on:
    branch: dev
after_deploy:
  - pip install libpysat